[ui]
hideTopBar = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#e2001a"
backgroundColor = "#f7f7f7"
secondaryBackgroundColor = "#f2f2f2"
textColor = "#000000"
linkColor = "#e2001a"
borderColor = "#6e6e6e"
showWidgetBorder = true
baseRadius = "0"
headingFontWeights = [600, 600, 600, 500, 500, 500]
